name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_android:
    name: Build Android app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3.11.0
        with:
          java-version: "12.x"
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true
      - name: Get Dependencies
        run: flutter pub get
      - name: Build Apk
        run: flutter build apk
#       - name: Upload a Build apk artifact
#         uses: actions/upload-artifact@v3.1.2
#         with:
#           name: apk-artifact
#           path: 
